# Generated by Django 5.0.4 on 2024-04-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(help_text='Informe o nome completo do atendente', max_length=100, verbose_name='Nome do atendente')),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(help_text='Informe o nome completo do médico', max_length=100, verbose_name='nome do medico')),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField(auto_now_add=True)),
                ('data_consulta', models.DateField()),
                ('relato_paciente', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('laudo', models.TextField(blank=True)),
                ('medicacao', models.CharField(blank=True, max_length=250)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao_programinha.atendente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao_programinha.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao_programinha.paciente')),
            ],
        ),
    ]
