# Generated by Django 5.0.4 on 2024-04-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_programinha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
        migrations.RenameModel(
            old_name='Sintomas',
            new_name='Sintoma',
        ),
    ]
